name: mash
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: null
#  cloud_firestore: null
  # cloud_firestore: ^4.17.2
  confetti: null
  cupertino_icons: ^1.0.6
  dev: ^1.0.0
  dio: ^5.4.2+1f
  equatable: ^2.0.5
  shimmer: ^3.0.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5

  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  go_router: ^13.2.4
  google_fonts: null
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  line_icons: null
  otp_text_field: null
  path_provider: ^2.1.3
  device_info_plus: ^10.1.0
  firebase_auth: ^4.19.5
  uuid: ^4.4.0
  lottie: ^3.1.2
  cloud_firestore: ^4.17.3
  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0
  google_maps_flutter: ^2.2.8
  location: ^6.0.2
  flutter_polyline_points: ^2.0.0
  flutter_emoji_feedback: ^0.3.0

  xml: ^6.5.0

  image: ^4.2.0
  geolocator: ^12.0.0
  flutter_pdfview: ^1.3.2
  get_it: ^7.7.0
  animations: ^2.0.11
  image_picker:
  photo_view:
  url_launcher:
  table_calendar: ^3.1.1
  flutter_cashfree_pg_sdk: ^2.1.2+32
  fluttertoast: ^8.2.6
  rive: ^0.11.7
  vocsy_epub_viewer: ^2.0.0
  animated_rating_bar: ^0.0.8
  just_audio: ^0.9.38
  flick_video_player: ^0.8.0
  video_player: ^2.8.7

  permission_handler: ^11.3.1
  flutter_download_manager: ^0.5.5
  flutter_file_dialog: ^3.0.2
  share_plus: ^9.0.0
  easy_image_viewer: ^1.5.0
  webview_flutter: ^4.8.0

  awesome_notifications: ^0.9.3+1
  image_picker_android: ^0.8.12+3
  path_provider_android: ^2.2.7






dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter 
  hive_generator: ^2.0.1


  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/mash_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/backgrounds/
    - assets/riv/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: fonts/sofi_pro_regular.otf
          weight: 900
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
